alldare:
  auth:
    issuer-uri: ${AUTH_ISSUER_URI:http://localhost:9000}
  admin:
    default:
      login: ${DEFAULT_ADMIN_LOGIN:admin}
      password: ${DEFAULT_ADMIN_PASSWORD:}

spring:
  application:
    name: alldare-auth
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/alldare_auth}
    username: ${SPRING_DATASOURCE_USERNAME:alldare_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  security:
    oauth2:
      authorizationserver:
        issuer: ${AUTH_ISSUER_URI:http://localhost:9000}
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:google-id}
            client-secret: ${GOOGLE_SECRET:google-secret}
            scope: openid, profile, email
          github:
            client-id: ${GITHUB_CLIENT_ID:github-id}
            client-secret: ${GITHUB_SECRET:github-secret}
            scope: read:user, user:email

server:
  port: 9000
  forward-headers-strategy: native

logging:
  level:
    online.alldare.auth: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.hibernate.SQL: INFO
